services:
  omni_robot_slam:
    build:
      context: .
    image: omni_robot_slam_img  
    container_name: omni_robot_slam  
    environment:
      # GUI variables
      - DISPLAY=$DISPLAY 
      - QT_X11_NO_MITSHM=1 
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      # GUI volumes
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    # network settings
    network_mode: host  
    # extra settings
    stdin_open: true
    tty: true  
    restart: unless-stopped